In [ ]:
pip install numpy

In [3]:
import numpy as np

In [ ]:
liste = [1, 2 ,3, 4]
tab = np.array(liste)
print(tab)

[1 2 3 4]


In [ ]:
# Créaon d'un tableau
tableau = np.array([[10, 20], [30, 40]])
print(tableau)

[[10 20]
 [30 40]]


In [ ]:
tableau_reshape = tableau.reshape(4)

In [ ]:
tableau_reshape

array([10, 20, 30, 40])

In [ ]:
# Aplar le tableau
tableau_flatten = tableau.flatten()
print("Tableau inial :\n", tableau)
print("Tableau redimensionné :", tableau_reshape)
print("tableau aplati:", tableau_reshape)

Tableau inial :
 [[10 20]
 [30 40]]
Tableau redimensionné : [10 20 30 40]
tableau aplati: [10 20 30 40]


In [ ]:
# Générer des nombres aléatoires
random_uniform = np.random.rand(3, 3) # Uniforme entre 0 et 1
random_normal = np.random.randn(3, 3) # Distribuon normale
print("Tableau aléatoire (uniforme) :\n", random_uniform)
print("Tableau aléatoire (normale) :\n", random_normal)

Tableau aléatoire (uniforme) :
 [[0.52384205 0.64828834 0.8862134 ]
 [0.45015204 0.90077429 0.49552347]
 [0.28198235 0.93904055 0.74291874]]
Tableau aléatoire (normale) :
 [[-0.59484013 -1.29482794 -0.08288166]
 [-0.89937421  0.21834662 -0.32081033]
 [ 0.99397134  1.06743897  1.99871853]]


In [ ]:
tableau = tableau *1.1
tableau

<ipython-input-28-2835066789c7>:1: RuntimeWarning: divide by zero encountered in divide
  tableau = tableau / 0


array([inf, inf, inf, inf])

# Nouvelle section

In [7]:
# Créaon des colonnes
arrondissement = np.array(["6e", "18e", "7e", "19e", "8e", "13e", "4e", "20e", "11e", "16e", np.nan,
"15e", "1er", "14e", "12e"])

surface = np.array([85, 55, 120, 70, 150, 65, 90, 60, 75, 110, 80, np.nan, 40, 200, 30])

nombre_pieces = np.array([3, 2, 4, np.nan, 5, 2, 3, 2, 3, 4, 3, 4, 1, 2, 10])

prix_vente = np.array([1330250, 381700, 1858800, 519400, 2457000, 491400, 1420200, 553860, 794250,
1295900, 950000, 1100000, 5000000, 300000, 800000])

# Combiner les colonnes dans un tableau NumPy
dataset = np.column_stack((arrondissement, surface, nombre_pieces, prix_vente))

# Combinaison des colonnes
dataset = np.array([arrondissement, surface, nombre_pieces, prix_vente]).T
dataset

array([['6e', '85.0', '3.0', '1330250'],
       ['18e', '55.0', '2.0', '381700'],
       ['7e', '120.0', '4.0', '1858800'],
       ['19e', '70.0', 'nan', '519400'],
       ['8e', '150.0', '5.0', '2457000'],
       ['13e', '65.0', '2.0', '491400'],
       ['4e', '90.0', '3.0', '1420200'],
       ['20e', '60.0', '2.0', '553860'],
       ['11e', '75.0', '3.0', '794250'],
       ['16e', '110.0', '4.0', '1295900'],
       ['nan', '80.0', '3.0', '950000'],
       ['15e', 'nan', '4.0', '1100000'],
       ['1er', '40.0', '1.0', '5000000'],
       ['14e', '200.0', '2.0', '300000'],
       ['12e', '30.0', '10.0', '800000']], dtype='<U32')

In [ ]:
dataset

array([['6e', '85.0', '3.0', '1330250'],
       ['18e', '55.0', '2.0', '381700'],
       ['7e', '120.0', '4.0', '1858800'],
       ['19e', '70.0', 'nan', '519400'],
       ['8e', '150.0', '5.0', '2457000'],
       ['13e', '65.0', '2.0', '491400'],
       ['4e', '90.0', '3.0', '1420200'],
       ['20e', '60.0', '2.0', '553860'],
       ['11e', '75.0', '3.0', '794250'],
       ['16e', '110.0', '4.0', '1295900'],
       ['nan', '80.0', '3.0', '950000'],
       ['15e', 'nan', '4.0', '1100000'],
       ['1er', '40.0', '1.0', '5000000'],
       ['14e', '200.0', '2.0', '300000'],
       ['12e', '30.0', '10.0', '800000']], dtype='<U32')

In [ ]:
indices_nan = []
for i in range(len(dataset)):
  if np.isnan(surface[i]) or np.isnan(nombre_pieces[i] or arrondissement[i] == 'nan'):
    indices_nan.append(i)

In [ ]:
indices_nan

[3, 11]

In [ ]:
dataset

array([['6e', '85.0', '3.0', '1330250'],
       ['18e', '55.0', '2.0', '381700'],
       ['7e', '120.0', '4.0', '1858800'],
       ['19e', '70.0', 'nan', '519400'],
       ['8e', '150.0', '5.0', '2457000'],
       ['13e', '65.0', '2.0', '491400'],
       ['4e', '90.0', '3.0', '1420200'],
       ['20e', '60.0', '2.0', '553860'],
       ['11e', '75.0', '3.0', '794250'],
       ['16e', '110.0', '4.0', '1295900'],
       ['nan', '80.0', '3.0', '950000'],
       ['15e', 'nan', '4.0', '1100000'],
       ['1er', '40.0', '1.0', '5000000'],
       ['14e', '200.0', '2.0', '300000'],
       ['12e', '30.0', '10.0', '800000']], dtype='<U32')

In [ ]:
# Augmenter les prix de vente de 10 %
prix_vente_augmentes = prix_vente * 1.1
prix_vente_augmentes

array([1463275.,  419870., 2044680.,  571340., 2702700.,  540540.,
       1562220.,  609246.,  873675., 1425490., 1045000., 1210000.,
       5500000.,  330000.,  880000.])

In [ ]:
# Mission:

# Générer des % aléatoires compris entre 5 % et 15 %
pourcentage_renovation = np.random.uniform(0.05, 0.15, len(prix_vente))

# Calculer les couts de rénovation
cout_renovation = prix_vente_augmentes * pourcentage_renovation

In [ ]:
cout_renovation

array([161541.83005346,  45238.31146609, 170674.91176312,  65205.87771874,
       328568.55147997,  45997.51335782, 116142.16467545,  53840.02411699,
        54404.04072627, 138893.82477148,  76977.61595058,  98018.15263605,
       316007.96359106,  43111.15300071,  82091.07107465])

In [ ]:
dataset = np.column_stack((dataset, prix_vente_augmentes, cout_renovation))
dataset

array([['6e', '85.0', '3.0', '1330250', '161541.8300534599',
        '1463275.0000000002', '161541.8300534599'],
       ['18e', '55.0', '2.0', '381700', '45238.31146609198',
        '419870.00000000006', '45238.31146609198'],
       ['7e', '120.0', '4.0', '1858800', '170674.91176312068',
        '2044680.0000000002', '170674.91176312068'],
       ['19e', '70.0', 'nan', '519400', '65205.87771873851', '571340.0',
        '65205.87771873851'],
       ['8e', '150.0', '5.0', '2457000', '328568.55147996853',
        '2702700.0', '328568.55147996853'],
       ['13e', '65.0', '2.0', '491400', '45997.51335781962', '540540.0',
        '45997.51335781962'],
       ['4e', '90.0', '3.0', '1420200', '116142.16467544745',
        '1562220.0000000002', '116142.16467544745'],
       ['20e', '60.0', '2.0', '553860', '53840.02411699468', '609246.0',
        '53840.02411699468'],
       ['11e', '75.0', '3.0', '794250', '54404.04072627238',
        '873675.0000000001', '54404.04072627238'],
       ['16e', 

In [ ]:
# calculer le nouveau prix après rénovation
nouveau_prix = prix_vente * 1.35

# stack
dataset = np.column_stack((dataset, nouveau_prix))
dataset

array([['6e', '85.0', '3.0', '1330250', '161541.8300534599',
        '1463275.0000000002', '161541.8300534599', '1795837.5000000002'],
       ['18e', '55.0', '2.0', '381700', '45238.31146609198',
        '419870.00000000006', '45238.31146609198', '515295.00000000006'],
       ['7e', '120.0', '4.0', '1858800', '170674.91176312068',
        '2044680.0000000002', '170674.91176312068', '2509380.0'],
       ['19e', '70.0', 'nan', '519400', '65205.87771873851', '571340.0',
        '65205.87771873851', '701190.0'],
       ['8e', '150.0', '5.0', '2457000', '328568.55147996853',
        '2702700.0', '328568.55147996853', '3316950.0'],
       ['13e', '65.0', '2.0', '491400', '45997.51335781962', '540540.0',
        '45997.51335781962', '663390.0'],
       ['4e', '90.0', '3.0', '1420200', '116142.16467544745',
        '1562220.0000000002', '116142.16467544745', '1917270.0000000002'],
       ['20e', '60.0', '2.0', '553860', '53840.02411699468', '609246.0',
        '53840.02411699468', '747711.0'],

In [ ]:
# calculer les loyers avant et apres rénovation
loyer_avant = (prix_vente*0.03)/12
loyer_apres = (prix_vente_augmentes * 0.035)/12

In [ ]:
dataset = np.column_stack((dataset, loyer_avant, loyer_apres))

In [ ]:
# Mask

array = np.array([1,2,3,4,5,6])
mask = array % 2 #division euclidienne
print(mask)

[1 0 1 0 1 0]


In [ ]:
array < 2

array([ True, False, False, False, False, False])

In [ ]:
# Mask exemple 2
array [array <= 2 ] = 0
array

array([0, 0, 3, 4, 5, 6])

In [ ]:
 prix_marchandise = np.array ([10, 15, 3500, -2, 5]) #brosses à dents

In [ ]:
mask = (prix_marchandise > 0) & (prix_marchandise < 100)
prix_filtrés = prix_marchandise[mask]

prix_filtres = prix_marchandise[(prix_marchandise > 0) & (prix_marchandise < 100) ]

prix_filtrés

array([10, 15,  5])

In [ ]:
# slicing & indexation:

# array[start:stop(non inclus):step]

In [ ]:
# 1D
array_1D = np.array([1,2,3,4,5,6,7,8])

In [ ]:
print(array_1D[0:7:2])

[1 3 5 7]


dans notre formule on a 0:5
5 correspond au stop non inclus (indice 5) >> 6
0 correspond au start >> 1

In [ ]:
print(array_1D[2:6])

[3 4 5 6]


In [ ]:
print(array_1D[1:])

[2 3 4 5 6 7 8]


In [ ]:
# extraire les elements entre les indice 2 et 7 avec un pas de 3
print(array_1D[2:7:3])

[3 6]


# Multidimensionnel n = 2

# array[start1:stop1:step1, start2:stop2:step2]


*   start1:stop1:step1 slicing de notre premiere dimension
*   start2:stop2:step2 slicing de notre premiere dimension




In [ ]:
tableau_2D = np.array([[1,2,3],[4,5,6],[7, 8, 9]])
tableau_2D

# 1ligne / 1colonne c est des vecteurs 1D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# la première colonne
print(tableau_2D[: , 0])

[1 4 7]


In [ ]:
# la première ligne
print(tableau_2D[0, :])

In [ ]:
# quel est l element qui appartient à la seconde(1) ligne et la 3 eme colonne(2)
print(tableau_2D[1,-1])

6


*features* == colonne
*individu* == lignes

"sportif JO" et on veut tous les ages de tous sportif sans répitition

In [ ]:
# tous les element de la 1 ere et la derniere colonne
print(tableau_2D[:,[0,-1]])

[[1 3]
 [4 6]
 [7 9]]


In [ ]:
# tous les element de la 1 ere ligne et tous les elements de la derniere colonne
1 #  tous les elements  de la L1 + avoir tous les element de C2
result = np.concatenate((tableau_2D[0, :], tableau_2D[:,-1]))
result = np.unique(result)
result


array([1, 2, 3, 6, 9])

In [ ]:
# kaggle
# paperwithcode state of art

In [ ]:
tableau_2D = tableau_2D/2
tableau_2D

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [ ]:
# Stack
arrondissement = dataset [:, 0]
surface = dataset[:, 1].astype(float).reshape(-1,1)


In [ ]:
dataset[:, 1]

array(['85.0', '55.0', '120.0', '70.0', '150.0', '65.0', '90.0', '60.0',
       '75.0', '110.0', '80.0', 'nan', '40.0', '200.0', '30.0'],
      dtype='<U32')

In [ ]:
surface

array([[ 3.],
       [ 2.],
       [ 4.],
       [nan],
       [ 5.],
       [ 2.],
       [ 3.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 3.],
       [ 4.],
       [ 1.],
       [ 2.],
       [10.]])

In [ ]:
tableau_arr_surface = np.hstack((arrondissement.reshape(-1, 1), surface))
tableau_arr_surface


array([['6e', '85.0'],
       ['18e', '55.0'],
       ['7e', '120.0'],
       ['19e', '70.0'],
       ['8e', '150.0'],
       ['13e', '65.0'],
       ['4e', '90.0'],
       ['20e', '60.0'],
       ['11e', '75.0'],
       ['16e', '110.0'],
       ['nan', '80.0'],
       ['15e', 'nan'],
       ['1er', '40.0'],
       ['14e', '200.0'],
       ['12e', '30.0']], dtype='<U32')

In [ ]:
tableau_arr_surface.shape

(15, 2)

In [ ]:
prix_vente.reshape(-1,1).shape

(15, 1)

In [ ]:
tableau_fusionné = np.hstack((tableau_arr_surface, prix_vente.reshape(-1,1)))
tableau_fusionné

array([['6e', '85.0', '1330250'],
       ['18e', '55.0', '381700'],
       ['7e', '120.0', '1858800'],
       ['19e', '70.0', '519400'],
       ['8e', '150.0', '2457000'],
       ['13e', '65.0', '491400'],
       ['4e', '90.0', '1420200'],
       ['20e', '60.0', '553860'],
       ['11e', '75.0', '794250'],
       ['16e', '110.0', '1295900'],
       ['nan', '80.0', '950000'],
       ['15e', 'nan', '1100000'],
       ['1er', '40.0', '5000000'],
       ['14e', '200.0', '300000'],
       ['12e', '30.0', '800000']], dtype='<U32')

Mme leroy
profil: jeune professionnelle
capital: 350000
contraintes:


1.   studio ou T1 (1 ou 2 piece)
2.   prix au m² inférieur à 10 000 euro
3.   situé dans les arrondissements centraux (1,2,3,4)
4.   loyer mensuel minimum de 1200 euro


filtrer les appartements pour Mme leroy !




In [ ]:
# mask pour nan
mask_surface = np.isnan(surface)
mask_nombre_pieces = np.isnan(nombre_pieces)

In [ ]:
mask_nan = mask_surface | mask_nombre_pieces # ou
indices_nan = np.where(mask_nan)[0]

# une fois l indice obtenu, on suprime de l index de notre dataset

In [ ]:
valid_mask = ~mask_surface & ~mask_nombre_pieces # et

In [ ]:
# Somme des éléments d'un tableau

# reduce(array)
a = np.array([1, 2, 3, 4])

result = np.add.reduce(a) # Applique l'additon cumulée
print(result) # 10 (1 + 2 + 3 + 4)


10


In [ ]:
# Accumulate
# Somme Accumulate
#Calcule les résultats cumulé le long d'un axe

a = np.array([1,2,3,4])
result = np.add(a, a)
result2 = np.add.accumulate(a)
result3 = np.multiply.accumulate(a)

print("opération avec Add sur tableau a:", result)
print("opération avec Add + accumulate sur tableau a:", result2)
print("opération avec multiply + accumulatesur tableau a:", result3)


opération avec Add sur tableau a: [2 4 6 8]
opération avec Add + accumulate sur tableau a: [ 1  3  6 10]
opération avec multiply + accumulatesur tableau a: [ 1  2  6 24]


In [ ]:
# Accumulate
# Somme Accumulate
#Calcule les résultats cumulé le long d'un axe

a = np.array([1,2])
b = np.array([0,1])
result = np.add(a, a)
print(result)


[2 4]


In [ ]:
# Mathématiques de base
# https://numpy.org/devdocs/reference/ufuncs.html

# addition soustraction multiplication et la division

a = np.array([1,2,3, 4])
b = np.array([4,5,6,7])


print("addition:", np.add(a, b))
print("soustraction", np.subtract(a, b))
print("multiplicationb", np.multiply(a,b))
print("division", np.divide(a, b))


addition: [ 5  7  9 11]
soustraction [-3 -3 -3 -3]
multiplicationb [ 4 10 18 28]
division [0.25       0.4        0.5        0.57142857]


In [ ]:
np.multiply.accumulate(a)

array([ 1,  2,  6, 24])

In [ ]:
np.pi

3.141592653589793

In [ ]:
# Trigo
# np.sin, np.cos, np.tan

angles = np.array([0, np.pi/2, np.pi])

# Sinus
print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
# exponentielle et logarithmes


print(np.exp(a))
print(np.log(a))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


In [ ]:
b

array([4, 5, 6, 7])

In [ ]:
# comparaison
# superieur = greater
print(np.greater(a,a))
# inferieur = less
print(np.less(a, a))
# égal = equal
print(np.equal(a,a))


[False False False False]
[False False False False]
[ True  True  True  True]


In [ ]:
# Création des colonnes
arrondissement = np.array(["6e", "18e", "7e", "19e", "8e", "13e", "4e", "20e", "11e", "16e", "2e",
"15e", "1er", "14e", "12e"])

surface = np.array([85, 55, 120, 70, 150, 65, 90, 60, 75, 110, 80, np.nan, 40, 200, 30])

nombre_pieces = np.array([3, 2, 4, np.nan, 5, 2, 3, 2, 3, 4, 3, 4, 1, 2, 10])

prix_vente = np.array([1330250, 381700, 1858800, 519400, 2457000, 491400, 1420200, 553860, 794250,
1295900, 950000, 1100000, 5000000, 300000, 800000])

# Combiner les colonnes dans un tableau NumPy
dataset = np.column_stack((arrondissement, surface, nombre_pieces, prix_vente))

In [ ]:
dataset

array([['6e', '85.0', '3.0', '1330250'],
       ['18e', '55.0', '2.0', '381700'],
       ['7e', '120.0', '4.0', '1858800'],
       ['19e', '70.0', 'nan', '519400'],
       ['8e', '150.0', '5.0', '2457000'],
       ['13e', '65.0', '2.0', '491400'],
       ['4e', '90.0', '3.0', '1420200'],
       ['20e', '60.0', '2.0', '553860'],
       ['11e', '75.0', '3.0', '794250'],
       ['16e', '110.0', '4.0', '1295900'],
       ['nan', '80.0', '3.0', '950000'],
       ['15e', 'nan', '4.0', '1100000'],
       ['1er', '40.0', '1.0', '5000000'],
       ['14e', '200.0', '2.0', '300000'],
       ['12e', '30.0', '10.0', '800000']], dtype='<U32')

In [ ]:
# on calcule la moyenne en ignorant les nan pour chaque colonne
Col_means = np.nanmean(data, axis = 0)
# on remplace les nan par la moyenne corespondante
indice_nan = np.isnan(data)
data[indice_nan] = np.take(Col_means, np.where(indice_nan)[1])
data

array([[8.50000e+01, 3.00000e+00, 1.33025e+06],
       [5.50000e+01, 2.00000e+00, 3.81700e+05],
       [1.20000e+02, 4.00000e+00, 1.85880e+06],
       [1.50000e+02, 5.00000e+00, 2.45700e+06],
       [6.50000e+01, 2.00000e+00, 4.91400e+05],
       [9.00000e+01, 3.00000e+00, 1.42020e+06],
       [6.00000e+01, 2.00000e+00, 5.53860e+05],
       [7.50000e+01, 3.00000e+00, 7.94250e+05],
       [1.10000e+02, 4.00000e+00, 1.29590e+06],
       [8.00000e+01, 3.00000e+00, 9.50000e+05],
       [4.00000e+01, 1.00000e+00, 5.00000e+06],
       [2.00000e+02, 2.00000e+00, 3.00000e+05],
       [3.00000e+01, 1.00000e+01, 8.00000e+05]])

In [ ]:
# calculer le prix au m² pour chaque bien immobilier
# utiliser une ufunc pour divisier le prix de vente par la surface

# prix_m_carre = prix de vente / surface
print(np.divide(prix_vente, surface))

[ 15650.           6940.          15490.           7420.
  16380.           7560.          15780.           9231.
  10590.          11780.90909091  11875.                     nan
 125000.           1500.          26666.66666667]


In [ ]:
c = np.array([1,2,3,4, np.nan])

In [ ]:
moyenne = (1+2+3+4)/4
moyenne

2.5

In [ ]:
c2 = np.array([1,2,3,4,2.5])
moyenne_c2 = (1+2+3+4+2.5)/5
moyenne_c2

2.5

In [ ]:
# traitement des nan:
# on va remplacer les nan par la moyenne de la colonne

surface_moyenne = np.nanmean(surface)
prix_vente_moyenne = np.nanmean(prix_vente)

In [ ]:
np.where(np.isnan(surface))

(array([11]),)

In [ ]:
data = dataset.copy()

# On a supprimé la première colonne
data = np.delete(data, 0, axis = 1)
data = np.delete(data, [3,11],axis = 0)

# argument de delete : jeu de donnée, indice , axis)
# axis = 0 >>>> lignes
# axis = 1 >>>> colonnes

data = np.array(data, dtype=float)

In [ ]:
# calcul du metre carre
price_m2 = np.divide(data[:,2], data[:,0])
price_m2

array([ 15650.        ,   6940.        ,  15490.        ,  16380.        ,
         7560.        ,  15780.        ,   9231.        ,  10590.        ,
        11780.90909091,  11875.        , 125000.        ,   1500.        ,
        26666.66666667])

In [ ]:
# calculer la somme totale des surfaces et prix de vente

print("total_Surface:", np.sum(data[:,0]))
print("total_price:", np.sum(data[:,2]))

total_Surface: 1160.0
total_price: 17633360.0


In [ ]:
data

array([[8.50000e+01, 3.00000e+00, 1.33025e+06],
       [5.50000e+01, 2.00000e+00, 3.81700e+05],
       [1.20000e+02, 4.00000e+00, 1.85880e+06],
       [1.50000e+02, 5.00000e+00, 2.45700e+06],
       [6.50000e+01, 2.00000e+00, 4.91400e+05],
       [9.00000e+01, 3.00000e+00, 1.42020e+06],
       [6.00000e+01, 2.00000e+00, 5.53860e+05],
       [7.50000e+01, 3.00000e+00, 7.94250e+05],
       [1.10000e+02, 4.00000e+00, 1.29590e+06],
       [8.00000e+01, 3.00000e+00, 9.50000e+05],
       [4.00000e+01, 1.00000e+00, 5.00000e+06],
       [2.00000e+02, 2.00000e+00, 3.00000e+05],
       [3.00000e+01, 1.00000e+01, 8.00000e+05]])

In [ ]:
# calcul par add
print("total_Surface:", np.add.reduce(data[:,0]))
print("total_price:", np.add.reduce(data[:,2]))

In [ ]:
# Numpy et la statistique descriptive
z = data[:,0]
mean = np.mean(z)
mediane = np.median(z)
ecart_type = np.std(z)
variance = np.var(z)
min = np.min(z)
max = np.max(z)
somme = np.sum(z)
quantiles = np.percentile(z, 25)

In [ ]:
statistique = np.array([mean, mediane, ecart_type, variance, min, max, somme, quantiles])
statistique

array([  89.23076923,   80.        ,   44.8864445 , 2014.79289941,
         30.        ,  200.        , 1160.        ,   60.        ])

In [ ]:
z

array([ 85.,  55., 120., 150.,  65.,  90.,  60.,  75., 110.,  80.,  40.,
       200.,  30.])

In [ ]:
# normaliser et standardiser les colonne surface et prix_vente:
# surface
normalized_data = (z - min)/(max-min)
# standardisation
standardized_data = (z - mean)/ ecart_type

Questions (Set 2 : Vrai/Faux)


1.   La fonction np.arange(10) crée un tableau avec les valeurs de 1 à 10.

*   Faux
*   Car on crée un tableau avec 10 élément allant de la valeur 0 à 9


2.  L'attribut size d'un tableau NumPy donne le nombre total d'éléments dans le tableau.

*   Vrai

3. La méthode np.ones((3, 4)) crée un tableau rempli de 1 avec 3 lignes et 4 colonnes.

*   Vrai

4. La méthode .T transpose un tableau NumPy.


*   Vrai

5. NumPy permet de travailler avec des valeurs infinies à l'aide de np.inf.

*   Vrai

6. la division par zéro dans numpy renvoie toujours une erreur

*   Faux   

7. La méthode np.cancatenate() peut etre utlisé pour fusionner des tableaux le long d'un axe

*  Vrai

8. la méthode np.max() retourne uniquement la valeur maximale d'un tableau 1D

* Vrai

9. les masks de firtrage ne fonctionnent qu'avec des tableau 1D

*   Faux



In [ ]:
a = ([1,2])
b = 3

np.add(a, b)

array([4, 5])

In [ ]:
data = np.array(data, dtype=float)
np.max(data)

5000000.0

In [ ]:
data

array([[8.50000e+01, 3.00000e+00, 1.33025e+06],
       [5.50000e+01, 2.00000e+00, 3.81700e+05],
       [1.20000e+02, 4.00000e+00, 1.85880e+06],
       [1.50000e+02, 5.00000e+00, 2.45700e+06],
       [6.50000e+01, 2.00000e+00, 4.91400e+05],
       [9.00000e+01, 3.00000e+00, 1.42020e+06],
       [6.00000e+01, 2.00000e+00, 5.53860e+05],
       [7.50000e+01, 3.00000e+00, 7.94250e+05],
       [1.10000e+02, 4.00000e+00, 1.29590e+06],
       [8.00000e+01, 3.00000e+00, 9.50000e+05],
       [4.00000e+01, 1.00000e+00, 5.00000e+06],
       [2.00000e+02, 2.00000e+00, 3.00000e+05],
       [3.00000e+01, 1.00000e+01, 8.00000e+05]])

In [ ]:
# calcul du max de la colonne 0 donc premiere colonne
np.max(data[:,0])

# calcul du max de la ligne 5 donc premiere colonne
np.max(data[5,:])

1420200.0

In [ ]:
# Calcul des max par colonne

np.max(data, axis = 0)

# Calcul de la moyenne par colonne

np.mean(data, axis = 0)


array([8.92307692e+01, 3.38461538e+00, 1.35641231e+06])

Set 2

1. Les ufunc peuvent produire plusieurs entrée ou sorties

*   Vrai

2. les ufunc sont des fonctions optimisé pour effectuer des opérations élémentaire sur des tableaux

*   Vrai

3. np.greater et np.less sont des fonctions ufunc

*   Vrai

4. la méthode np.reshape() modifie le tableau d'origine et retourne une nouvelle vue du même tableau avec une forme différente

*   Faux

5. La fonction flatten sert à quoi


In [ ]:
A = np.array([[1,2,3],[4,5,6]])
A.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
A = A.reshape(6)
A

array([1, 2, 3, 4, 5, 6])